import type { Metadata } from "next";
import Link from "next/link";
import { Geist, Geist_Mono } from "next/font/google";
import { Stack } from "@mui/material";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
        <Stack direction="row" columnGap={4}>
          <Link href="/">Home</Link>
          <Link href="/trimVideo">Trim Video</Link>
          <Link href="/spliceVideos">Splice Videos Together</Link>
          <Link href="/thumbnailSelector">Thumbnail Selection</Link>
          <Link href="/webm">WebM thumbnail selection</Link>
          <Link href="/CustomVideoPlayer">CustomVideoPlayer</Link>
        </Stack>
        {children}
      </body>
    </html>
  );
}
